### PR TITLE
feat: add an optimized version of the logo

### PR DESCRIPTION
**Pull request by Conaclos**
Hi!

I am currently updating the biome README.
I noticed that the logo have to be cropped.
I take the opportunity to improve the logo:

- I improved the `B` path by smoothing out some ugly curves (this is only noticeable when the logo is zoomed in)
- I optimized the logo by hand 
- Finally, I used [SVGO](https://github.com/svg/svgo) to optimize the size of the logo

This results in a 8 times reduction in file size.

### CODE REVIEW

**Comment by ematipico** [comment]
We should update ALL the resources with the new logo.

**Comment by Conaclos** [comment]
Do we really need all these variants of the logo? This logo and an icon version (with black and white background variants) should be enough?

**Comment by ematipico** [comment]
> Do we really need all these variants of the logo? This logo and an icon version (with black and white background variants) should be enough?

I think so. I just uploaded all the resources I could get, so everyone had everything

**Comment by Conaclos** [comment]
@ematipico Updated :)

**Review by ematipico — APPROVED** [review]
Great stuff!! Could you add `.DS_Store` to `.gitignore` if you want? Merge it whenever you want :)

**Pull request merged**
